environment:
  matrix:
  - COMPILER: MSVC_16
    ARCHITECTURE: x86
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
#  - COMPILER: MSVC_16
#    ARCHITECTURE: x64
#    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019

build:
  verbosity: detailed
  parallel: true

cache:
  - c:\tools\vcpkg\installed\
  - c:\tools\vcpkg\downloads\

install:
  - cd c:\Tools\vcpkg
  - git pull
  - .\bootstrap-vcpkg.bat -disableMetrics
  - vcpkg.exe integrate install
  - vcpkg.exe install sqlite3:x86-windows

before_build:
  - cd c:\projects\playci
  - IF "%ARCHITECTURE%" == "x86" IF "%COMPILER%" == "MSVC_16" call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\vsdevcmd.bat" -arch=x86 -host_arch=x64
#  - IF "%ARCHITECTURE%" == "x64" IF "%COMPILER%" == "MSVC_16" call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\vsdevcmd.bat" -arch=x64 -host_arch=x64

build_script:
  - mkdir build_vs2019
  - cd build_vs2019
  - cmake -DCMAKE_GENERATOR_PLATFORM=win32 -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake -G  "Visual Studio 16" ..
  - cmake --build . --config debug -j 18
